<?php 
$collection = $this->getItems();
?>
<style>
.home-ad {
    background: url("<?php echo $this->getSkinUrl('images/media/imageshow/big/img_switch_bottom_bg.gif');?>") no-repeat scroll left bottom transparent;
    height: 341px;
    position: relative;
	overflow:hidden;
	margin-left:<?php echo $this->getMarginLeft(); ?>px;
	margin-top:<?php echo $this->getMarginRight(); ?>px;
	margin-bottom:<?php echo $this->getMarginBottom(); ?>px;
}
.pics {  
    height:  232px;  
    width:   232px;  
    padding: 0;  
    margin:  0;  
} 
#pages {
    padding-left: 5px;
    position: absolute;
    top: 308px;
    z-index: 99;
}
#pages a.activeSlide {
    background: url("<?php echo $this->getSkinUrl('images/media/imageshow/big/img_switch_nav_selected.gif');?>") no-repeat scroll center center transparent;
}
#pages a {
    background: url("<?php echo $this->getSkinUrl('images/media/imageshow/big/img_switch_nav.gif');?>") no-repeat scroll center center transparent;
    color: #596878;
    display: block;
    float: left;
    font-weight: bold;
    height: 26px;
    line-height: 26px;
    margin-left: 5px;
    text-align: center;
    width: 25px;
	outline: medium none;
    text-decoration: none;
}
</style>
<div id="imageshow_big" class="home-ad" style="display:none;">
	<div id="pics">
	<?php if($collection = $this->getItems()): ?>
	<?php 
foreach($collection as $item):
?>
<a href="<?php echo $item->getHref(); ?>" alt="<?php echo $item->getTitle(); ?>" title="<?php echo $item->getTitle(); ?>"><img width="<?php echo $this->getImageWidth()?>px" height="<?php echo $this->getImageHeight()?>px" src="<?php echo $item->getImageUrl();?>" /></a>
<?php endforeach; ?>
<?php else: ?>
		<a href="http://www.baidu.com" alt="" title=""><img width="920px" height="330px" src="<?php echo $this->getSkinUrl('images/media/imageshow/big/img_switch_01.jpg');?>" /></a>
		<a href="http://www.baidu.com" alt="" title=""><img width="920px" height="330px" src="<?php echo $this->getSkinUrl('images/media/imageshow/big/img_switch_02.jpg');?>" /></a>
		<a href="http://www.baidu.com" alt="" title=""><img width="920px" height="330px" src="<?php echo $this->getSkinUrl('images/media/imageshow/big/img_switch_03.jpg');?>" /></a>
		<a href="http://www.baidu.com" alt="" title=""><img width="920px" height="330px" src="<?php echo $this->getSkinUrl('images/media/imageshow/big/img_switch_04.jpg');?>" /></a>
		<a href="http://www.baidu.com" alt="" title=""><img width="920px" height="330px" src="<?php echo $this->getSkinUrl('images/media/imageshow/big/img_switch_05.jpg');?>" /></a>
<?php endif?>
	</div>
</div>
<script>
//  使用append方法，把原来的位置挪到合适的位置就可以了
jQuery(document).ready(function(){		
	var $ = jQuery;
	var $imageshow_big = $("#imageshow_big");
	var $baseElement = $("<?php echo $this->getBaseElement(); ?>");
	$baseElement.<?php echo $this->getInsertType(); ?>($imageshow_big);
	$imageshow_big.show();
	$('#pics').before('<div id="pages">').cycle({  
		fx:'<?php echo $this->getCycleType(); ?>',					
		timeout:<?php echo $this->getTimeout(); ?>,	
		speed:<?php echo $this->getSpeed(); ?>,		
		pager:'#pages'		
	});
});
</script>